package ca.jay.jac444;



public class TestThrow1 {

	private String exceptionName = "";
	
	private TestThrow1(String _eName)
	{
		this.exceptionName = _eName;
		
	}
	
	class innerTest {
		
		private String name = "";
		
		private innerTest(String _name)
		{
			this.name = _name;
		}
		
		private String getName()
		{
			return name + exceptionName;
		}
		
		private void setName(String _name)
		{
			this.name = _name;
		}
		
	}
	
   static void validate(int age) {
		if(age<18)
		  throw new ArithmeticException("notÂ valid");
		else
		  System.out.println("welcome to vote");
   }

	public static void main(String args[])
	{
		try
		{
			TestThrow1 test = new TestThrow1("Jongkuk");
			test.validate(13);
			
			
			
			
			//validate(13);
		}
		catch(Exception e)
		{
			System.out.println(e.toString());
			e.printStackTrace();
			
		}
		finally
		{
			System.out.println("rest of the code1");			
		}
		
		System.out.println("rest of the code2");		
	}
}
